Subfolders: [GUI]
Joystick:
  file: Joystick
  varclass: Joystick
  frequency: 100
ProfileA:
  file: ControlProfile
  varclass: ControlProfile
  frequency: 1
  activate: 'A'
  max_percentage: 100
  formula_modifier: 30
ProfileB:
  file: ControlProfile
  varclass: ControlProfile
  frequency: 1
  activate: 'B'
  max_percentage: 70
  formula_modifier: 50
ProfileC:
  file: ControlProfile
  varclass: ControlProfile
  frequency: 1
  activate: 'C'
  max_percentage: 50
  formula_modifier: 50
ProfileD:
  file: ControlProfile
  varclass: ControlProfile
  frequency: 1
  activate: 'D'
  max_percentage: 30
  formula_modifier: 50
ThrusterPower:
  file: Thruster_Power
  varclass: Thruster_Power
  frequency: 1
Thrusters:
  file: Thrusters
  varclass: Thrusters
  frequency: 10
EM1:
  device: EM1
  file: EM
  varclass: EM
  frequency: 1
  address: 0x30
EM2:
  device: EM2
  file: EM
  varclass: EM
  frequency: 1
  address: 0x32
Gripper:
  file: Gripper
  varclass: Gripper
  frequency: 1
  device: gripper
  address: 0x22
  speed: 10000 # 0 - 32767
Erector:
  file: Gripper
  varclass: Gripper
  frequency: 1
  device: erector
  address: 0x21
  speed: 8000
## Logger:
##  file: Logger
##  varclass: Logger
##  frequency: 1
##  Print: True
##  Log: True
##  Topics: "Thruster" #All Topicss: gamepad, command, Thruster, info, can, log
CAN_Handler:
  file: CAN_Handler
  varclass: CAN_Handler
  frequency: 1
GUI:
  file: GUI
  varclass: GUI
  frequency: 30
MoveForward:
  file: Move_Forward
  varclass: Move_Forward
  frequency: 10
  start_countdown: 0.5
  duration: 10
  power: 1
_TestCaseSend:
  file: GUI
  varclass: TestCaseSend
  frequency: 30
# pubsender:
#    file: pubsender
#    varclass: pubsender
#    frequency: 1
# cpub:
#   file: socketpubsub
#   varclass: cpub
#   ip: 192.168.3.15
#   port: 8080
#   config_file: serverconfig.yaml
#   frequency: 1
# pubsender2:
#    file: pubsender
#    varclass: pubsender2
#    frequency: 1
# pubreceiver:
#    file: pubsender
#    varclass: pubreceiver
#    frequency: 1
# spub:
#    file: socketpubsub
#    varclass: spub
#    frequency: 1
_Module_Manager:
  terminal_frequency: 150
